### ISSUE TITLE
Replace html_entity_decode with a more restrictive function

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/fin-ad-base-theme#40]
I'm worried about the use of `html_entity_decode` as it appears to allow for arbitrary HTML input by users of any role. I would discourage the use of HTML entities in shortcode attributes in general. https://github.com/washingtonstateuniversity/fin-ad-base-theme/blob/master/includes/shortcode-cards.php#L60

This seems like a place where the shortcode itself could be best wrapped around content and the `$content` argument could be used along with `wp_kses_post()` to better ensure proper output of content.

`[contact_cards name="abcdefg"]This is my description[/contact_cards]`

allows for...

`function cards_shortcode( $atts, $content ) { echo wp_kses_post( $content ); }`

**Comment by quantumJLBass** [comment]
Fair enough, makes perfect sense :-)  Will get to that shortly

**Comment by quantumJLBass** [comment]
addressed in 5cdc101 both in the tinymce button and the hand written shortcode
