### ISSUE TITLE
PHP warning in production

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/fin-ad-base-theme#43]
Saw this entry in the PHP error logs in production today. Let me know if any more info would help.

```
2016/09/08 11:33:09

PHP Warning:  Invalid argument supplied for foreach() in /var/www/wp-content/themes/wsu-finance-administration/inc/builder.php on line 56

stage.payroll.wsu.edu/hows-our-website/
GET /wp-admin/post.php?post=29&action=edit
```

**Comment by quantumJLBass** [comment]
Thanks for the heads up I'll go clear that

**Comment by quantumJLBass** [comment]
oddly enough in the dev is doesn't and hasn't showen up.  The check should resolve.  I'll leave this open for a bit and if no word I'll close it.

**Comment by quantumJLBass** [comment]
the lack of reproduction of error allowed for neutral logic to slip by.  

Reset timer
